// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArcoCrudForm: typeof import('./src/components/ArcoCrudForm.vue')['default']
    ArcoCrudTable: typeof import('./src/components/ArcoCrudTable.vue')['default']
  }
}
